[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fyodorov_utils"
version = "0.2.71"
authors = [
    { name="Daniel Ransom", email="02masseur.alibis@icloud.com" },
]
description = "Library for creating LLM-based agents with tools and RAG"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/FyodorovAI/fyodorov-llm-agents"
Issues = "https://github.com/FyodorovAI/fyodorov-llm-agents/issues"

[tool.setuptools.packages.find]
where = ["src"]
